### PR TITLE
fix(metadata): Fixed suggested flags

### LINKED ISSUE #29: Suggested flag shouldn't be there for all pipelines
_From @invincibleJai on March 22, 2018 16:59_

In pipelines response https://forge.api.prod-preview.openshift.io/api/services/jenkins/pipelines we get suggested: true for all pipelines. I don't think it'll make sense to show all pipelines as suggested. I believe suggested should be shown based on user-selected Runtime/Mission.That is, considering we're working from a dynamic list of mission & runtime choices.

_Copied from original issue: fabric8-launcher/launcher-planning#137_

### PR DESCRIPTION
**Pull request by gastaldi**
Fixes #29

### CODE REVIEW

**Comment by gastaldi** [comment]
@rupalibehera can you review and merge this PR asap?

**Comment by gastaldi** [comment]
@rupalibehera can you review and merge this PR asap?

**Comment by jaseemabid** [comment]
@gastaldi If you look at the project, you can see that none of the current build team members have any commits on the project; there is a good chance that you know about this more than the rest of us combined. We could use your judgement here and merge it. I'm just saying that the current build team really shouldn't be maintaining this library.

**Comment by gastaldi** [comment]
@jaseemabid afaik we have discussed the ownership of this repository in a SoS meeting (I don't remember the exact date) and it was agreed that the Build team would own this repository and review any PRs sent to it.  This repository was maintained by James and was assigned to the Build team after they left the company

This repository provides the Jenkinsfiles that the Jenkins in OSIO requires to run the builds, if you're saying that the current build team shouldn't be maintaining this library, then I guess we have bigger problems /cc @krishnapaparaju

**Comment by rupalibehera** [comment]
copying the discussion of MM here https://chat.openshift.io/developers/pl/uwjbm5a1ft859rhdfko1yx1ihh
As already said I do not understand it completely.
Merging this PR

**Pull request merged**
