### PR TITLE
Fix: maven integration tests

### PR DESCRIPTION
**Pull request by hrishin**
Maven integration tests are failing because it tries to create a
test namespace (project) on OpenShift, hence call to OpenShift API gets
fail due to permission issue.
This patch fixes the `mavenCI` step by inputting maven command to run
integration test along with valid test namespace.

Resolves:
 - https://github.com/openshiftio/openshift.io/issues/3134
 - https://github.com/openshiftio/openshift.io/issues/763

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Marking it as WIP so that we can test it out first

**Comment by hrishin** [comment]
@bartoszmajsak PR https://github.com/fabric8io/fabric8-pipeline-library/pull/420 is merged. 
Shall we test it now?

**Comment by hrishin** [comment]
@bartoszmajsak @sthaha could you please review it?

**Review by piyush-garg — APPROVED** [review]
Tested this PR, works fine, CI passes. LGTM

**Comment by sthaha** [comment]
@hrishin Although I merged it, @piyush1594 pointed that the target branch is `fabric8io:it-test-fix` shouldn't this be master instead? 

/cc @bartoszmajsak

**Comment by hrishin** [comment]
@sthaha, agreed here. That's what we have discussed over the last call between @bartoszmajsak , you and me, right?
Because @bartoszmajsak want to `test` it before merging it into master.  Please let me know if I'm missing something.

**Comment by sthaha** [comment]
@hrishin we have merged the change to master see: https://github.com/fabric8io/fabric8-jenkinsfile-library/pull/37

**Comment by piyush-garg** [comment]
@sthaha @hrishin I think all good here now. I discussed this with @hrishin in morning. I think we can delete the other branch. @hrishin WDYT?

**Pull request merged**
