### PR TITLE
Update master

### PR DESCRIPTION
**Pull request by piyush-garg**

### CODE REVIEW

**Comment by piyush-garg** [comment]
@gastaldi Are we maintaining the master branch here and other branches should need to be there or not?

**Comment by gastaldi** [comment]
@piyush1594 only the master branch of this repository is used in launcher-backend

**Comment by piyush-garg** [comment]
@gastaldi Thanks for the info, one more information. There is one more branch, is that exist before also or we just created it by mistake because of this PR #36

**Review by sthaha — APPROVED** [review]

**Comment by piyush-garg** [comment]
@gastaldi How to reflect it in launcher-backend?

**Comment by gastaldi** [comment]
@piyush1594 I have no idea if anyone is using the `it-test-fix` branch, otherwise it can be removed. I'll trigger a build in launcher-backend in a few minutes and update production. I'll let you know when that gets percolated

**Comment by piyush-garg** [comment]
cool, awesome. Thanks a lot @gastaldi

**Comment by gastaldi** [comment]
@piyush1594 updated

**Comment by piyush-garg** [comment]
Tested, works. Thanks a lot.

**Pull request merged**
